# Generated by Django 5.0.6 on 2024-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_excerpt_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
